repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        args: ["--unsafe"]
      - id: end-of-file-fixer
        exclude: ^(\.mypy_cache)
      - id: trailing-whitespace
        exclude: ^(\.mypy_cache)
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.12
  - repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
      - id: interrogate
        exclude: "^(tests/|deprecated/|notebooks/|old_notebooks/|configs/)"
        args: [-v, --fail-under=80, --ignore-module]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
  - repo: https://github.com/mxab/pre-commit-trivy.git
    rev: v0.17.0
    hooks:
      - id: trivyfs-docker
        args:
          - --skip-dirs
          - ./tests
          - .
      - id: trivyconfig-docker
        args:
          - --skip-dirs
          - ./tests
          - .
